import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/SideBar";
import MainNav from "@/components/MainNav";
import { Plus_Jakarta_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Analytics Dashboard",
	description: "Generated by create next app",
	icons: {
		icon: "/icons/logo.svg",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={jakarta.className}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<section className="max-md:-translate-x-[200%] transition-transform duration-500 ease-in-out">
						<SideBar />
					</section>

					<MainNav />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
